/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'submissionTime' : Time,
  'projectDetails' : IDL.Text,
});
export const ContactFormData = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'projectDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func([Project], [], []),
  'getAllContactForms' : IDL.Func([IDL.Principal], [IDL.Vec(ContactForm)], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'submitContactForm' : IDL.Func([ContactFormData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'submissionTime' : Time,
    'projectDetails' : IDL.Text,
  });
  const ContactFormData = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  
  return IDL.Service({
    'addProject' : IDL.Func([Project], [], []),
    'getAllContactForms' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ContactForm)],
        [],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'submitContactForm' : IDL.Func([ContactFormData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };